version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: redis

    webserver:
      image: nginx:alpine
      container_name: nginx
      working_dir: /application
      volumes:
          - ./code/site1:/application/site1
          - ./code/site2:/application/site2
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./log/nginx:/var/log/nginx
      ports:
       - "80:80"

    php-fpm-site1:
      build: docker/php-fpm-site1
      container_name: php-fpm-site1
      working_dir: /application/site1
      volumes:
        - ./code/site1:/application/site1
        - ./docker/php-fpm-site1/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    php-fpm-site2:
      build: docker/php-fpm-site2
      container_name: php-fpm-site2
      working_dir: /application/site2
      volumes:
        - ./code/site2:/application/site2
        - ./docker/php-fpm-site2/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini